apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - master-statefulset.yaml
  - slave-statefulset.yaml
  - sentinel-statefulset.yaml
  - service.yaml

commonLabels:
  component: redis
  managed-by: kustomize
