apiVersion: v1
kind: Service
metadata:
  name: accounting-service
  labels:
    app: accounting-service
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: http
  selector:
    app: accounting-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounting-service-config
data:
  db.host: "postgres"
  db.port: "5432"
  db.name: "accountingdb"
  # 회계 처리 배치 사이즈
  accounting.batch.size: "500"
