apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shop-msa

resources:
  - namespace.yaml
  - postgresql
  - redis
  - kafka

labels:
  - pairs:
      project: shop-msa
      managed-by: kustomize
      tier: infrastructure