apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - zookeeper-statefulset.yaml
  - kafka-statefulset.yaml
  - service.yaml

commonLabels:
  component: kafka-cluster
