apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - redis-master-statefulset.yaml
  - redis-replica-statefulset.yaml
  - redis-sentinel-statefulset.yaml
  - service.yaml

commonLabels:
  component: redis-sentinel
