apiVersion: v1
kind: Service
metadata:
  name: partner-service
  labels:
    app: partner-service
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: http
  selector:
    app: partner-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: partner-service-config
data:
  db.host: "postgres"
  db.port: "5432"
  db.name: "partnerdb"
