apiVersion: v1
kind: Service
metadata:
  name: partner-service
  namespace: microservices
  labels:
    app: partner-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: partner-service
  ports:
  - name: http
    port: 8084
    targetPort: 8084
    protocol: TCP
