apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - zookeeper-statefulset.yaml
  - statefulset.yaml
  - service.yaml

commonLabels:
  component: kafka
  managed-by: kustomize
