spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/partnerdb
    username: partnerservice
    password: test_partner_password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
  
  kafka:
    bootstrap-servers: localhost:9092

# TEST - CORS
management:
  endpoints:
    web:
      cors:
        allowed-origins:
        - http://localhost:8080
        - http://localhost:8084
        allowed-methods:
          - "*"
        allowed-headers:
          - "*"
        allow-credentials: true

logging:
  level:
    root: INFO
    "[com.shop.payment]": DEBUG
    "[org.springframework.web]": DEBUG
    "[org.hibernate.SQL]": DEBUG