apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shop-msa

resources:
  - ../api-gateway
  - ../user-service
  - ../payment-service
  - ../settlement-service
  - ../partner-service
  - ../accounting-service

labels:
  - pairs:
      project: shop-msa
      managed-by: kustomize
      tier: application