apiVersion: v1
kind: Service
metadata:
  name: accounting-service
  namespace: microservices
  labels:
    app: accounting-service
    tier: backend
    critical: "true"
spec:
  type: ClusterIP
  selector:
    app: accounting-service
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
