spring:
  # redis:
  #   sentinel:
  #     master: mymaster
  #     nodes:
  #     - localhost:26379
  #   timeout: 3000ms
  #   lettuce:
  #     pool:
  #       max-active: 8
  #       max-idle: 8
  #       min-idle: 0
  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
        - localhost:26379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  cloud:
    gateway:
      # routes:
      # - id: user-service
      #   uri: http://localhost:8081
      #   predicates:
      #   - Path=/api/users/**
      server:
        webflux:
          routes:
          - id: user-service
            uri: http://localhost:8081
            predicates:
            - Path=/api/users/**
        # - id: payment-service
        #   uri: http://localhost:8082
        #   predicates:
        #     - Path=/api/payments/**
        
        # - id: settlement-service
        #   uri: http://localhost:8083
        #   predicates:
        #     - Path=/api/settlements/**
        
        # - id: partner-service
        #   uri: http://localhost:8084
        #   predicates:
        #     - Path=/api/partners/**
        
        # - id: accounting-service
        #   uri: http://localhost:8085
        #   predicates:
        #     - Path=/api/accounting/**

logging:
  level:
    root: INFO
    "[com.payment.gateway]": DEBUG
    "[io.lettuce.core]": DEBUG
    "[io.lettuce.core.protocol]": DEBUG
    "[io.lettuce.core.cluster]": DEBUG
    # "[org.springframework.data.redis]": DEBUG
    # "[org.springframework.data.redis.connection]": DEBUG
    # "[org.springframework.data.redis.connection.lettuce]": DEBUG
    # "[io.netty]": DEBUG
    # "[io.netty.handler.logging]": DEBUG
    # "[org.springframework.boot.autoconfigure]": DEBUG