apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 네임스페이스 설정
namespace: shop-msa

# 모든 리소스 포함
resources:
  - namespace.yaml
  - postgresql
  - api-gateway
  - user-service
  - payment-service
  - settlement-service
  - partner-service
  - accounting-service
  - redis
  - kafka

# 공통 레이블 추가
commonLabels:
  project: shop-msa
  managed-by: kustomize
