apiVersion: v1
kind: Service
metadata:
  name: settlement-service
  namespace: microservices
  labels:
    app: settlement-service
    tier: backend
    critical: "true"
spec:
  type: ClusterIP
  selector:
    app: settlement-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
